[package]
name = "pyo3-backtrace-repro"
version = "0.1.0"
authors = ["Clemens Winter <clemens@openai.com>"]
edition = "2018"

[lib]
name = "pyo3_backtrace_repro"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.9.0-alpha.1"
features = ["extension-module"]

